### ISSUE TITLE
404 Error on File Edit ?

### ISSUE THREAD

**Issue by ghost** [AOKP/packages_apps_ROMControl#59]
Since some weeks it's not possibile to edit from value-de the strings.xml or arrays.xml file.
It shows all the time the following error:

http://img707.imageshack.us/img707/6708/unbenanntlky.png

404 - This is not the web space you are looking for.

What's going on there? :)

**Comment by KhasMek** [comment]
I don't quite understand what you're asking, but it sounds like maybe your URL is wrong. Is this what you are looking for?

https://github.com/AOKP/packages_apps_ROMControl/tree/ics/res/values-de

**Comment by ghost** [comment]
Oops, I think the error description was not really good on the first post...

The problem is, that the 404 error appears when I try to edit strings.xml (for example) with "Fork and edit this file" and click "Propose File Change".

**Comment by KhasMek** [comment]
I'd delete your local branch (here https://github.com/archiv/packages_apps_ROMControl ) which is way behind in commits and try it again.

**Comment by ghost** [comment]
Thanks KhasMek!
